In [1]:
import os
import scanpy as sc
import numpy as np
import pandas as pd
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter
# from tools.formating.formating import change_file_extension, load_anndata, convert_from_r, convert_to_r
pandas2ri.activate()

In [2]:
ro.r['source']('seurat_qc.R')
RunSeuratQC_r = ro.globalenv['RunSeuratQC']
path="hca_heart_neuronal_raw.h5ad"
adata_path = 'hca_heart_neuronal_raw.h5ad'
results = list(RunSeuratQC_r(path, 'hca_heart_neuronal_raw.h5seurat', adata_path=adata_path))

R[write to console]: Loading required package: SummarizedExperiment

R[write to console]: Loading required package: MatrixGenerics

R[write to console]: Loading required package: matrixStats

R[write to console]: 
Attaching package: ‘MatrixGenerics’


R[write to console]: The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiff


    an issue that caused a segfault when used with rpy2:
    https://github.com/rstudio/reticulate/pull/1188
    Make sure that you use a version of that package that includes
    the fix.
    

R[write to console]: Attaching SeuratObject

R[write to console]: Seurat v4 was just loaded with SeuratObject v5; disabling v5 assays and
validation routines, and ensuring assays work in strict v3/v4
compatibility mode

R[write to console]: 
Attaching package: ‘Seurat’


R[write to console]: The following object is masked from ‘package:SummarizedExperiment’:

    Assays


R[write to console]: Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat

R[write to console]: Signac built for for SeuratObject v4 was just loaded with SeuratObject
v5; disabling v5 assays and validation routines, and ensuring assays
work in strict v3/v4 compatibility mode

R[write to console]: 
Attaching package: ‘Matrix’


R[write to console]: The following object is masked from ‘package:S4Vectors’:

    expand


R[write to console]: X -> counts



Formal class 'Seurat' [package "SeuratObject"] with 13 slots
  ..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "SeuratObject"] with 8 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:2957496] 26 39 52 53 54 78 122 152 168 178 ...
  .. .. .. .. .. ..@ p       : int [1:3437] 0 3033 3600 4041 4764 5192 5642 6295 6838 8098 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 33538 3436
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:33538] "MIR1302-2HG" "FAM138A" "OR4F5" "AL627309.1" ...
  .. .. .. .. .. .. ..$ : chr [1:3436] "AACCCAAAGTACGAGC-1-H0015_apex" "AACGAAACACGACTAT-1-H0015_apex" "AAGTGAATCGAGAGCA-1-H0015_apex" "AAGTGAATCTGATTCT-1-H0015_apex" ...
  .. .. .. .. .. ..@ x       : num [1:2957496] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i   

R[write to console]: Performing log-normalization

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to conso

[1] "Finding variable features."


R[write to console]: Calculating gene variances
R[write to console]: 

R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]

[1] "Scaling dataset."


R[write to console]: Centering and scaling data matrix

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |==========                                                   

[1] "Running PCA."


R[write to console]: PC_ 1 
Positive:  LAMA2, RYR2, TTN, PTPRG, MAML2, FBXL7, GRIK2, PRKG1, RORA, ZFPM2 
	   SLC8A1, ABCA9-AS1, CTNNA3, ABCA9, CBLB, ZEB1, BICC1, CACNA1C, AP002518.2, SOX5 
	   EBF1, LRRTM4, KAZN, ARHGAP10, FGF12, PDE3A, NAV2, AC007319.1, ACSM3, ARL15 
Negative:  CALM2, RPL18A, CD59, RPL26, RPL39, OAZ1, RPS27, RPL21, RPS18, RPL9 
	   RPL7, RPL3, RPL34, TMSB4X, RPL32, RPS14, FTL, COX6A1, RPL12, RPS19 
	   HSPE1, NEDD8, LGALS1, VAMP2, B2M, FKBP1A, RPS15A, RPS15, ARL2, RPL23A 
PC_ 2 
Positive:  PID1, ACSM3, VIT, DCLK1, EBF2, EGFR, ACSM1, FOXP2, MGST1, PLA2G5 
	   COL4A4, ADH1B, CARMIL1, EBF1, PDGFD, C7, LHFPL6, COL6A3, KAZN, PRKG1 
	   BNC2, AC007319.1, MSC-AS1, ABCA10, SOBP, FMO2, COL4A3, MECOM, UNC5C, ARHGAP10 
Negative:  NPPA, CD9, NPPB, CRYAB, SPP1, PKN2-AS1, PMP22, GPX3, CLU, IL1RAPL2 
	   NFATC2, ALDH1A1, TMEM176A, HES1, S100A4, PLP1, CST3, MPZ, S100A6, TNNI3 
	   HS3ST3A1, UBASH3B, S100A1, CD14, LRRTM4, TNNT2, ALK, MYOT, RHOB, S100B 
PC_ 3 
Positive:  CLDN5, TMEM88,

Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 3436
Number of edges: 109553

Running Louvain algorithm...


R[write to console]: 0%   10   20   30   40   50   60   70   80   90   100%

R[write to console]: [----|----|----|----|----|----|----|----|----|----|

R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: *
R[write to console]: 

Maximum modularity in 10 random starts: 0.8468
Number of communities: 12
Elapsed time: 0 seconds


R[write to console]: Warning:
R[write to console]:  The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session

R[write to console]: 22:04:34 UMAP embedding parameters a = 0.9922 b = 1.112

R[write to console]: Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'

R[write to console]: Also defined by ‘spam’

R[write to console]: 22:04:34 Read 3436 rows and found 10 numeric columns

R[write to console]: 22:04:34 Using Annoy for neighbor search, n_neighbors = 30

R[write to console]: Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'

R[write to console]: Also defined by ‘spam’

R[write to console]: 22:04:34 Building Annoy index with metric = cosine, n_trees = 50

R[write to console]: 0%   10   20   30   40  

[1] "Seurat object is saved successfully."
[1] "Converting Seurat object to AnnData object."


In [3]:
print(results)

[array(['RNA'], dtype='<U3'), array(['RNA'], dtype='<U3'), array(['hca_heart_neuronal_raw.h5seurat'], dtype='<U31'), array(['hca_heart_neuronal_raw.h5ad'], dtype='<U27'), <rpy2.robjects.vectors.BoolVector object at 0x7f69ec577600> [RTYPES.LGLSXP]
R classes: ('logical',)
[       0]]


In [4]:
from rpy2.robjects import r, StrVector, NULL
from typing import Any, List, Optional

def convert_from_r(item: Any, date_cols: Optional[List[str]] = None, name: str = '', reserve_plots: bool = True) -> Any:
    """convert rpy object into python native object
    Args:
        item (Any): rpy2 object to convert
        date_cols (list[str], optional): define the date colums in R dataframe , in order to conevrt them into pandas datetime. Defaults to None.
        name (str, optional): name of the object to convert, (not required for external use). Defaults to ''.
        reserve_plots (bool, optional): if True prserve rpy2 ListVector as rpy2 ListVector if name conatains plot,
                                        in order to be able to ouput ggplot plots. Defaults to True.
    Returns:
        Any: the converted item
    """
    result = item
    remove_list: bool = True
    if item == ro.vectors.NULL:
        return None
    elif 'plot' in name and isinstance(item, ro.vectors.ListVector) and reserve_plots:
        return item
    elif isinstance(item, (ro.environments.Environment,
                           ro.Formula)):
        return None
    elif isinstance(item, ro.vectors.DataFrame):
        with localconverter(ro.default_converter + pandas2ri.converter):
            result = ro.conversion.rpy2py(item)
        result = convert_df_dates_from_r(result, date_cols)
        remove_list = False
    elif isinstance(item, (ro.vectors.StrVector,
                           ro.vectors.FloatVector,
                           ro.vectors.BoolVector,
                           ro.vectors.IntVector)):
        result = tuple(item)
    elif isinstance(item, ro.vectors.ListVector):
        if item.names == ro.vectors.NULL:
            return None
        result = {}
        remove_list = False
        if len(item) > 0:
            result = dict(zip(item.names, list(item)))
            for k, v in result.items():
                result[k] = convert_from_r(v, date_cols, name=k)
    if '__len__' in result.__dir__() and len(result) == 1 and remove_list:
        result = result[0]
    return result

In [5]:
if results[0] != ro.rinterface.NULL:
    default_assay = list(results[0])[0]
    assay_names = list(results[1])
    output = list(results[2])[0]
    adata_path = list(results[3])[0]
    ddl_assay_names = convert_from_r(list(results[4])[0])
    print("Type of ddl_assay_names:", type(ddl_assay_names))
    print("Value of ddl_assay_names:", ddl_assay_names)
else:
    raise RuntimeError(f"Seurat QC failed.")

Type of ddl_assay_names: <class 'bool'>
Value of ddl_assay_names: False


In [6]:
output

'hca_heart_neuronal_raw.h5seurat'

In [7]:
adata_path

'hca_heart_neuronal_raw.h5ad'

In [8]:
adata = sc.read_h5ad(adata_path)
adata

AnnData object with n_obs × n_vars = 3436 × 33538
    obs: 'orig.ident', 'n_counts', 'n_genes', 'nCounts_RNA', 'nFeatures_RNA', 'NRP', 'age_group', 'cell_source', 'cell_type', 'donor', 'gender', 'percent_mito', 'percent_ribo', 'region', 'sample', 'scrublet_score', 'source', 'type', 'version', 'cell_states', 'Used', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable'
    obsm: 'X_pca', 'X_tsne', 'X_umap'
    layers: 'scale.data'

In [15]:
adata.X.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
adata.layers['scale.data']

array([[ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.0281569 , ..., -0.06304653,
         0.        ,  0.        ]])

In [24]:
from umap import UMAP

if not ddl_assay_names:
    if os.path.exists(adata_path):
        print("Adding 3D UMAP to AnnData object.")
        sc.pp.neighbors(adata, n_neighbors=10, n_pcs=3, random_state=0)
        umap_3d = UMAP(n_components=3, init='random', random_state=0)
        adata.obsm["X_umap_3D"] = umap_3d.fit_transform(adata.obsm['X_pca'])
        # adata.obsm["X_umap_3D"] = adata_3D.obsm["X_umap"]
        adata.write_h5ad(adata_path, compression='gzip')
        adata_3D = None
    else:
        raise ValueError("AnnData file does not exist.")

Adding 3D UMAP to AnnData object.


/usr/local/lib/python3.8/dist-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")


In [25]:
adata

AnnData object with n_obs × n_vars = 3436 × 33538
    obs: 'orig.ident', 'n_counts', 'n_genes', 'NRP', 'age_group', 'cell_source', 'cell_type', 'donor', 'gender', 'nCounts_RNA', 'nFeatures_RNA', 'percent_mito', 'percent_ribo', 'region', 'sample', 'scrublet_score', 'source', 'type', 'version', 'cell_states', 'Used', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable'
    uns: 'neighbors'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_umap_3D'
    layers: 'scale.data'
    obsp: 'distances', 'connectivities'

In [26]:
adata.obsm['X_umap']

array([[ 4.73994233, 10.88068801],
       [ 0.05498769, -6.39408511],
       [-0.81740091, -5.91939848],
       ...,
       [-8.59770701,  5.80163509],
       [-9.05568335,  5.64351732],
       [-8.73765872,  5.65475685]])

In [27]:
adata.obsm['X_umap_3D']

array([[ 1.2389023 ,  0.17247425,  3.5108423 ],
       [-1.5085722 ,  1.0367727 ,  4.0758543 ],
       [-1.4218253 ,  0.23663785,  3.2739491 ],
       ...,
       [14.681225  , -0.38077277,  8.828661  ],
       [14.738458  , -0.43038186,  8.868302  ],
       [14.769193  , -0.45038512,  8.847239  ]], dtype=float32)